apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  db-username: YWRtaW4=            # 'admin' base64 encoded
  db-password: cGFzc3dvcmQ=        # 'password' base64 encoded
  api-key: YXBpa2V5MTIzNDU=        # 'apikey12345' base64 encoded
  secret-key: c2VjcmV0a2V5         # 'secretkey' base64 encoded
